export const DAAS_WORK = {
  id: 'work',
  eyebrow: 'Recent work',
  title: 'Work that helps businesses look funded.',
  description:
    'Brand systems, pitch-ready decks, product UI, campaign creatives, and event stage visuals — under one monthly plan.',
  ctaLabel: 'See pricing',
  ctaHref: '#pricing',
  capabilities: [
    'Pitch decks',
    'Product UI',
    'Framer sites',
    'Brand systems',
    'Campaign creatives',
    'Social media',
    'Landing pages',
    'Investor updates',
    'Conference branding',
    'LED stage loops',
    'Email design',
    'Brand guidelines',
    '+ more',
  ],
  items: [
    {
      id: 'abhyudaya-brand',
      title: 'Abhyudaya Ornaments',
      image: '/images/abhyudaya-ornaments.png',
      video: null,
      tag: 'Brand identity',
    },
    {
      id: 'abhyudaya-social',
      title: 'Festival campaign',
      image: '/images/abhyudaya-ornaments-vertical.png',
      video: null,
      tag: 'Social creatives',
    },
    {
      id: 'conference-stage',
      title: 'Summit stage loops',
      image: '/images/img/1.jpg',
      video: null,
      tag: 'LED / 4K',
    },
    {
      id: 'event-landing',
      title: 'Event registration page',
      image: '/images/img/2.jpg',
      video: null,
      tag: 'Landing pages',
    },
    {
      id: 'framer-saas',
      title: 'SaaS marketing site',
      image: '/images/img/3.jpg',
      video: null,
      tag: 'Framer',
    },
    {
      id: 'product-ui',
      title: 'B2B product UI',
      image: '/images/img/4.jpg',
      video: null,
      tag: 'UI/UX',
    },
    {
      id: 'ai-workflow',
      title: 'Brand workflow system',
      image: '/images/img/5.jpg',
      video: null,
      tag: 'AI systems',
    },
    {
      id: 'brand-refresh',
      title: 'Brand refresh',
      image: '/images/img/6.jpg',
      video: null,
      tag: 'Guidelines',
    },
  ],
};
